# Support Vector Machines
Load the `mnist` dataset. Split it into training and test sets. Train and test a support vector machine model using scikit-learn. Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [1]:
import pandas as pd #load data set
import sklearn.model_selection #split the data!!
import sklearn.metrics # to calculate accuracy!!!!
import sklearn.svm
import plotly.express as px

## Loading Dataset

In [2]:
df = pd.read_csv('/mnist.csv')
df = df.set_index('id')
df.head(3)

,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
id,,,,,,,,,,,,,,,,,,,,,
31953,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34452,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60897,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Splitting the data set

In [3]:
x = df.drop(['class'], axis=1)
y =df['class']

x_train, x_test, y_train, y_test, = sklearn.model_selection.train_test_split(x,y)

print('df', df.shape)
print('x_train', x_train.shape)
print('x_test', x_test.shape)
print('y_train', y_train.shape)
print('y_test', y_test.shape)

df (4000, 785)
x_train (3000, 784)
x_test (1000, 784)
y_train (3000,)
y_test (1000,)

## Training model

In [6]:
model = sklearn.svm.SVC()

model.fit(x_train, y_train)

SVC()

## Testing the model

In [8]:
y_predicted = model.predict(x_test)

accuracy = sklearn.metrics.accuracy_score(y_test, y_predicted)
accuracy

0.929

##  Hiperparameter Tuning

In [9]:
c_list = range(1, 10)
kernel_list = ['linear', 'poly', 'rbf', 'sigmoid']
result_df = pd.DataFrame(columns=['C', 'Kernel', 'Accuracy'])

for c in c_list:
    for kernel in kernel_list:
        model = sklearn.svm.SVC(C=c, kernel=kernel)
        model.fit(x_train, y_train)
        y_predicted = model.predict(x_test)
        accuracy = sklearn.metrics.accuracy_score(y_test, y_predicted)
        result_df = result_df.append({'C': c, "Kernel": kernel,"Accuracy": accuracy}, ignore_index=True)

result_df

    C   Kernel  Accuracy
0   1   linear     0.890
1   1     poly     0.906
2   1      rbf     0.929
3   1  sigmoid     0.860
4   2   linear     0.890
5   2     poly     0.916
6   2      rbf     0.933
7   2  sigmoid     0.843
8   3   linear     0.890
9   3     poly     0.919
10  3      rbf     0.932
11  3  sigmoid     0.842
12  4   linear     0.890
13  4     poly     0.918
14  4      rbf     0.933
15  4  sigmoid     0.830
16  5   linear     0.890
17  5     poly     0.918
18  5      rbf     0.935
19  5  sigmoid     0.834
20  6   linear     0.890
21  6     poly     0.921
22  6      rbf     0.935
23  6  sigmoid     0.813
24  7   linear     0.890
25  7     poly     0.921
26  7      rbf     0.935
27  7  sigmoid     0.816
28  8   linear     0.890
29  8     poly     0.921
30  8      rbf     0.936
31  8  sigmoid     0.809
32  9   linear     0.890
33  9     poly     0.922
34  9      rbf     0.936
35  9  sigmoid     0.803

## Visualization C x Acurracy

In [30]:
c_df = result_df[result_df['Kernel']=='rbf']

fig = px.line(x=c_df['C'], y=c_df['Accuracy'], labels={'x':'C', 'y':'Accuracy'})
fig.show()

In [37]:
kernel_df = result_df[result_df['C']==22]

fig = px.bar(kernel_df, x='Kernel', y='Accuracy')
fig.show()